sudo: requried
language: generic
services:
  - docker

before_install:
  - docker build -t andrewtjames/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run andrewtjames/react-test npm run test

after_success:
  - docker build -t andrewtjames/multi-client ./client
  - docker build -t andrewtjames/multi-nginx ./nginx
  - docker build -t andrewtjames/multi-server ./server
  - docker build -t andrewtjames/multi-worker ./worker
  # login in to docker form cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push all images up to docker hub
  - docker push andrewtjames/multi-client
  - docker push andrewtjames/multi-nginx
  - docker push andrewtjames/multi-server
  - docker push andrewtjames/multi-worker
